### ISSUE TITLE
unthreaded Perls OpenBSD

### ISSUE THREAD

**Issue by plicease** [plicease/FFI-Platypus#19]
libffi needs pthreads:

```
openbsd64% prove -bv t/closure_die.t
t/closure_die.t ..
1..2
/home/ollisg/perl5/perlbrew/perls/perl-5.18.2g/bin/perl:/usr/local/lib/libffi.so.0.0: undefined symbol 'pthread_mutex_lock'
lazy binding failed!
Failed 2/2 subtests

Test Summary Report
-------------------
t/closure_die.t (Wstat: 139 Tests: 0 Failed: 0)
  Non-zero wait status: 139
  Parse errors: Bad plan.  You planned 2 tests but ran 0.
Files=1, Tests=0,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.04 cusr  0.00 csys =  0.07 CPU)
Result: FAIL
```

The "fix" such as it is for `FFI::Raw` is here:

https://github.com/ghedo/p5-FFI-Raw/pull/29

**Comment by plicease** [comment]
This should be fixed for `Alien::FFI` 0.03 when `install_type=share`.

https://github.com/plicease/Alien-FFI/commit/53319bcb5e897fa99daf47fcbd1ce30e89e0f36f

The fix is wonky and I suspect the real fix is to produce a libffi that works on OpenBSD without pthreads.  Patches would be welcome for either `Alien::FFI` or `FFI::Platypus` (or `libffi` probably but that is not my project).  I find developing on OpenBSD to be very very very painful so I won't myself commit the time to figure this out.

I am marking `Alien::FFI` with `install_type=system` on unthreaded Perls to be an unsupported configuration.  If you can figure out how to make this work patches would be welcome, but since I am able to get unthreaded Perls to work with `install_type=share` I am going to mark this issue closed.

**Comment by tehmoth** [comment]
So the fix here to mark OpenBSD "system" installs of Alien::FFI as unsupported doesn't work
```
BEGIN {
  use Config;
  if($^O eq 'openbsd' && !$Config{usethreads} && Alien::FFI->install_type eq 'system')
  {
    print "Configuration not supported.\n";
    print "Please reinstall Alien::FFI with ALIEN_FORCE=1\n";
    print "See https://github.com/plicease/FFI-Platypus/issues/19\n";
    exit 0;
  }
```
Seems to be missing the use or require of Alien::FFI in the script.
```
.cpanm/work/1477202331.37881/FFI-Platypus-0.44:2341$ perl ./Build.PL
Can't locate object method "install_type" via package "Alien::FFI" (perhaps you forgot to load "Alien::FFI"?) at ./Build.PL line 4.
BEGIN failed--compilation aborted at ./Build.PL line 15.
```

Also it seems unnecessary as I was able to (after removing the above check, and having a system (ports) libffi and system, unthreaded perl) build, test and install FFI::Platypus on OpenBSD 6.0

The OpenBSD devel/libffi port added -pthread to libffi.pc in this revision
[(http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/devel/libffi/patches/patch-libffi_pc_in?rev=1.3&content-type=text/x-cvsweb-markup)] (part of the 6.0 release ports) which fixes the missing libpthread issue

**Comment by plicease** [comment]
Thank you very much for taking the time and reporting this.  My OpenBSD VM got trashed in a disk crash so I am unable to test this, but I will take you at your word and just remove the block.  I just sent a version to CPAN with this change (0.45).  Please let me know if this does not work for you.
