### ISSUE TITLE
Better documentation for non C programmers

### ISSUE THREAD

**Issue by plicease** [plicease/FFI-Platypus#20]
The documentation is definitely easier to understand if you know C.  This betrays my background with C and C++ obviously.  It would be great to have some guides specific to Platypus with these and other languages:

 - Fortran
 - Rust
 - Go
 - Assembly

Also:

 - C++ (I theorize this may be possible with c++filt or maybe clang has an API)

Also interspersing the documentation generally with some comments that will help non C programmers would be great.

**Comment by zmughal** [comment]
Have you seen this blog post: [Using Rust from Perl and Julia](http://paul.woolcock.us/posts/rust-perl-julia-ffi.html)? It might help with the Rust bit.

**Comment by plicease** [comment]
@zmughal fantastic!  Thanks I will definitely follow up on this!

**Comment by plicease** [comment]
Here be some stuff on Fortran:

**Comment by plicease** [comment]
Go:
http://stackoverflow.com/questions/6125683/call-go-functions-from-c

**Comment by plicease** [comment]
Tangentially I'd like to reserve a namespace such as `FFI::Platypus::Lang::{Rust,Go,Fortran}` for integration with other languages.  You'd be able to do something like `$ffi->with("Rust")` and you'd get rust aliases instead of C alias types.  That is to say `$ffi->type('int')` would be an error but `$ffi->type('i32')` (rust signed 32bit int) would work under a rust mode as well as `$ffi->type("sint32")` (which is an libffi type and is always visible).  The `::Lang::Foo` package could also provide hooks for `Module::Build::FFI` so to build any bundled code in the ffi directory.

**Comment by plicease** [comment]
`FFI::Platypus::Lang::Rust::Type::*` could be for custom types specific to particular languages.

Hopefully `::Lang::*` would be decoupled from the Platypus core and someone with appropriate knowledge for each language could take ownership.

**Comment by zmughal** [comment]
For C++, I've been keeping an eye what has been done in Julia with [Cpp.jl](https://github.com/timholy/Cpp.jl) and [Clang.jl](https://github.com/ihnorton/Clang.jl). I would like to use FFI to support bindings for the VTK library (a C++ library with many classes and no templating).

**Comment by plicease** [comment]
Thanks for linking the issue the links may be useful.

**Comment by plicease** [comment]
https://wiki.haskell.org/CPlusPlus_from_Haskell

**Comment by plicease** [comment]
I have a workin-ish example for C++ here:

https://github.com/plicease/Color-FFI

Numerous caveats:
  - it is decidedly not portable, depending on `-fkeep-inline-functions` to force `g++` to emit code for inlined functions (an option not supported by `clang` and presumably not MSVC++ either), the question is can we achieve similar capabilities on C++ compilers that we care about?
  - also explicitly links the .so against -lstdc++ because otherwise I was unable to resolve any symbols (this is probably only an issue for bundled code that comes with a Perl dist in the ffi directory).
  - I'm using `malloc` and `free` instead of `new` and `delete`, but it seems to work ??
  - You need to know what the size of the object is (or over allocate) I did this by adding a C function that just returns the size of the class.  In some cases that won't be possible.
  - Uses `c++filt` to map C++ names to their mangled forms.  Interfaces in `cxxabi.h` may be able to do something similar.
  - After getting this to work with a reference to an opaque pointer, I tried switching to using the new `record` type (a reference to a packed string), but that caused it to dump core in the test suite.  Not sure if that is a limitation of C++ or a bug in the new `record` code.

**Comment by plicease** [comment]
This is better addressed now that there are a number of foreign language plugins (C++, Fortran, Free Pascal, Rust, etc).  I am hoping these will be improved and/or adopted in time.  There is also a CAVEATS section that explains (but does not excuse :) my C/C++ bias.  PRs to improve the situation in the core or in the plugins are welcome.  I am closing this general issue so that more specific issues / PRs can be opened in the appropriate places.
