### ISSUE TITLE
Consider \$foo for 'opaque' type:

### ISSUE THREAD

**Issue by plicease** [plicease/FFI-Platypus#22]
The intuitive way:

http://blogs.perl.org/users/graham_ollis/2015/01/practical-ffi-with-platypus.html#comment-1531375

Existing way:

http://blogs.perl.org/users/graham_ollis/2015/01/practical-ffi-with-platypus.html#comment-1531383

No reason we can't support both.

**Comment by plicease** [comment]
One downside to this is that it isn't round trip, consider:

```
struct foo_t;

extern struct foo_t *foo (foo_t *);
```

and

```
type opaque => foo_t;
attach foo => [foo_t] => foo_t;
my $packed = pack ...;
my $pointer = foo(\$packed);
```

Whereas with an `int *` you pass in a \42 and get back a \42.

I'm not sure it is important though.

**Comment by plicease** [comment]
Another thing to consider: should we also support `\\$foo` for `opaque*` and `[\$foo]` for `opaque[]`

Getting a bit dizzy.

**Comment by plicease** [comment]
After sleeping on this, I think it is better to create a separate `record` type.  A `record` is a fixed sized region of memory, so you can do this:

```
type 'record <32>', 'foo_t';  # actual syntax up for debate
attach foo => ['foo_t'] => 'foo_t';
my $packed = pack ...;
my $also_packed = foo($packed);
```

The C `foo` gets the actual memory region for `$packed`, but `$also_packed` will be copied, so there are some caveats there.

As a bonus you should be able to do this:

```
my $copied_memory = cast opaque => 'record <112>' => $pointer;
```

**Comment by plicease** [comment]
Could also do:

```
type 'record (32)';
```

That allows us to later do something like:

```
type 'record (int a, int[32] b, string c)' => 'foo_t'
```

a la closures

**Comment by plicease** [comment]
Closing this for now, using `record` in favor of the `\$packed` notation for `opaque`.  We may down the road reconsider the `\$packed` notation.

**Comment by bakkiaraj** [comment]
Is "record" right word to use here? if I understand correctly, we are trying to read some memory bytes, Can it be struct than record? so its easy to co relate with C  code.

my $copied_memory = cast (opaque, 'struct',112,$pointer); 

Just a thought.

**Comment by plicease** [comment]
Fair question.  I picked record as the more generic term for what C calls a struct:

http://en.wikipedia.org/wiki/Record_(computer_science)

One of the goals is to be less C centric.  I also find it less awkward to talk about records in the documentation because it is a legal English word.  We could add 'struct' as an alias (a la pointer is an alias for opaque).
