### ISSUE TITLE
Integrate FFI::CheckLib directly?

### ISSUE THREAD

**Issue by awwaiid** [plicease/FFI-Platypus#30]
Docs say FFI::CheckLib is the way to go to identify libraries -- why not just integrate it directly like:

    $ffi->lib(find_lib => 'archive');

**Comment by plicease** [comment]
I did this sort of deliberately to keep Platypus and CheckLib decoupled.  I'd also like to keep the `lib` method to mean use literally this path to this library.  But maybe with appropriately documented caveats we could have a shortcut:

```
$ffi->find_lib( ... )
```

Or something like that?

**Comment by plicease** [comment]
This should go out with 0.20 soonish.
