### ISSUE TITLE
bump version of Config::AutoConf

### ISSUE THREAD

**Issue by zmughal** [plicease/FFI-Platypus#33]
`Config::AutoConf->check_prog_cc` first appeared in Config::AutoConf v0.306_001. Might as well bump it to the latest (v0.309).

[Diff](https://metacpan.org/diff/file?target=REHSACK/Config-AutoConf-0.306_001/&source=REHSACK/Config-AutoConf-0.305/).

**Comment by plicease** [comment]
Thanks for catching that.

**Comment by plicease** [comment]
fixed in 0.22 on its way to CPAN.
