### ISSUE TITLE
Active State Perl PPM is not building for FFI::Platypus

### ISSUE THREAD

**Issue by bakkiaraj** [plicease/FFI-Platypus#37]
In windows OS, ActiveState Perl provides nice utility called ppm, which will download the pre built perl modules from the ActiveState build environment and install in local machines.

This means, ActiveState perl user do not need to have development environment in the local machine to install perl modules.

As of now, FFI-Platypus is not available via ActiveState perl ppm.

http://code.activestate.com/ppm/FFI-Platypus/

Build Log: http://ppm4.activestate.com/MSWin32-x86-64int/5.20/2000/P/PL/PLICEASE/FFI-Platypus-0.23.d/log-20150216T061859.txt

From the build log, it appears that, ActivePerl severs have only 420 seconds for a module to build and test. It looks like FFI::Platypus test takes longer than 420s and it gets aborted and module is not available to consume via Active State perl PPM tool.

Its is possible to install this module via CPAN + having gcc in the windows PC but if its available via Active Perl PPM, it would reach more developer on windows.

Please optimize the test / remove low priority test / do not run all the test by default , So it would get build in Active State PPM server environment.

**Comment by bakkiaraj** [comment]
Sorry the real issue is in the PkgConfig module. Nothing to do with FFI-Platypus. Please ignore this issue #37.

**Comment by plicease** [comment]
I consider this a bug in ActiveState.  It does not take PkgConfig.pm 7 minutes to install on my Windows PC.  Further I don't understand why they have to build it from scratch for every package that declares it as a configure_requires.  Strawberry includes PkgConfig.pm as part of its extended core.

I don't use ActiveState anymore, but it would be desirable to work around this if possible.  Couple of solutions come to mind:

  - If we can detect a ppm build during test we can skip some, probably safely
  - If we can force a parallel `make test` it may also be faster
  - rework the PkgConfig.pm test suite to be more targeted

**Comment by plicease** [comment]
With the latest version of `PkgConfig.pm`, `FFI::Platypus` is now building on ActiveState MSWin32 32bit.  The 64 bit version is broken on an older version of `Shell::Config::Generate`, but I think 0.20 should fix that.

**Comment by plicease** [comment]
Once this gets integrated into `Alien::Base` it should improve the reliability of all `Alien::Base` stuff on other platforms:

https://github.com/Perl5-Alien/Alien-Base/pull/108

**Comment by bakkiaraj** [comment]
Ok. Great. Thanks for the info.

On Fri, Feb 20, 2015 at 8:55 PM, Graham Ollis <notifications@github.com>
wrote:

> With the latest version of PkgConfig.pm, FFI::Platypus is now building on
> ActiveState MSWin32 32bit. The 64 bit version is broken on an older version
> of Shell::Config::Generate, but I think 0.20 should fix that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plicease/FFI-Platypus/issues/37#issuecomment-75255446>
> .
>



-- 
Regards,
Bakkiaraj M
