### ISSUE TITLE
Help with Record Type?

### ISSUE THREAD

**Issue by frioux** [plicease/FFI-Platypus#58]
This is a combination feature request / call for some help.  Basically I'm working on a GPGME::FFI and ran into a little snag.  GPGME has the following type:

```c
struct _gpgme_engine_info
{
  struct _gpgme_engine_info *next;
  gpgme_protocol_t protocol;
  char *file_name;
  char *version;
  const char *req_version;
  char *home_dir;
};
```

There are two issues:

1. How can I (or is it even possible) to have a pointer to the same typed record?
2. If I have a predefined type (for example gpgme_protocol_t is an int) how can I reference it in the record?

If either of the above are not yet doable, maybe just create bugs for them.

**Comment by plicease** [comment]
I was able to get information from the `gpgme_get_engine_info` thusly:

```perl
use strict;
use warnings;
use 5.014;

package GPGME {

  use FFI::CheckLib;
  use FFI::Platypus;

  my $ffi = FFI::Platypus->new(lib => find_lib_or_die( lib => 'gpgme' ));

  package GPGME::EngineInfo {

    use FFI::Platypus::Record;
  
    record_layout(qw(
      opaque _next
      uint   protocol
      string file_name
      string version
      string req_version
      string home_dir
    ));
  
    sub next {
      my($self) = @_;
      # CAUTION: this copies the next record.
      # since we are only using it to read the
      # structure this my be okay.
      defined $self->_next ? $ffi->cast('opaque' => 'record(GPGME::EngineInfo)' => $self->_next) : undef;
    }

  }

  $ffi->type('uint' => 'gpgme_error_t');

  $ffi->attach('gpgme_get_engine_info' => ['record(GPGME::EngineInfo)'] => 'gpgme_error_t');

}

my $info = GPGME::EngineInfo->new;
my $error = GPGME::gpgme_get_engine_info($info);

if(!$error) {

  while(defined $info) {
  
    say "---";
    say "  protocol:    ", $info->protocol;
    say "  file_name:   ", $info->file_name;
    say "  version:     ", $info->version;
    say "  req_version: ", $info->req_version;
    say "  home_dir:    ", $info->home_dir;
    $info = $info->next;

  }

}
```

Here is the output:

```
---
  protocol:    0
  file_name:   
  version:     
  req_version: 
  home_dir:    
---
  protocol:    0
  file_name:   /usr/bin/gpg2
  version:     2.0.26
  req_version: 1.4.0
  home_dir:    
---
  protocol:    1
  file_name:   /usr/bin/gpgsm
  version:     
  req_version: 2.0.4
  home_dir:    
---
  protocol:    2
  file_name:   /usr/bin/gpgconf
  version:     2.0.26
  req_version: 2.0.4
  home_dir:    
---
  protocol:    3
  file_name:   /run/user/1000/keyring/gpg
  version:     1.0
  req_version: 1.0
  home_dir:    !GPG_AGENT
---
  protocol:    6
  file_name:   /nonexistent
  version:     1.0
  req_version: 1.0
  home_dir:    
```

notes:

 * I think I mentioned on IRC that `FFI::Platypus::Record` usually only makes sense if you are allocating the structures on the Perl side.  This is a weird function which you allocate one node, but the other nodes are allocated by libgpgme.  Each of the nodes in the linked list is copied into a new `F::P::Record` object (using the cast method), which I *think* is okay since we are only using this to read the structure.
 * pack/unpack may be faster though arguably less readable (?)

**Comment by plicease** [comment]
Closing as I think this is resolved.  Feel free to ping me here or IRC if anything else is unclear.

**Comment by frioux** [comment]
In case anyone is interested, [this commit](https://github.com/frioux/GPGME-FFI/commit/38ea39861b9731418f2d78aaca12639eb83a477a) was the result of the conversation.
