### ISSUE TITLE
[PATCH] fix spelling mistakes

### ISSUE THREAD

**Issue by gregoa** [plicease/FFI-Platypus#66]
In Debian we are currently applying the following patch to
FFI-Platypus.
We thought you might be interested in it too.

    Description: fix spelling mistakes
    Origin: vendor
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2016-06-27
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libffi-platypus-perl.git/plain/debian/patches/spelling.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by plicease** [comment]
applied, thanks!

**Comment by gregoa** [comment]
On Mon, 27 Jun 2016 11:04:47 -0700, Graham Ollis wrote:

> applied, thanks!

Great, thank you!


Cheers,
gregor

-- 
 .''`.  Homepage https://info.comodo.priv.at/ - OpenPGP key 0xBB3A68018649AA06
 : :' : Debian GNU/Linux user, admin, and developer -  https://www.debian.org/
 `. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
   `-
