### ISSUE TITLE
compiler error when installing via CPAN on raspberry pi

### ISSUE THREAD

**Issue by antichef** [plicease/FFI-Platypus#70]
hello - when I attempt to install FFI::Platypus using `perl -MCPAN -e shell` on a raspberry pi with uname - a output "Linux [name] 4.1.13-v7+ #826 SMP PREEMPT Fri Nov 13 20:19:03 GMT 2015 armv7l GNU/Linux", I consistently get the error:

cc -Iinclude -Ixs -I/usr/lib/perl/5.14/CORE -DXS_VERSION="0.43" -DVERSION="0.43" -fPIC -I/usr/local/share/perl/5.14.2/auto/share/dist/Alien-FFI/lib/libffi-3.2.1/include -c -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fstack-protector -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g -o lib/FFI/Platypus.o lib/FFI/Platypus.c
lib/FFI/Platypus.c: In function ‘XS_FFI__Platypus__API_arguments_get_sint8’:
lib/FFI/Platypus.c:771:1: error: unrecognizable insn:
(insn 234 233 235 12 (set (subreg:SI (reg/v:DI 208 [ RETVAL ]) 0)
        (sign_extend:SI (mem/s/j:QI (plus:SI (mult:SI (reg:SI 284)
                        (const_int 8 [0x8]))
                    (reg/f:SI 206 [ D.21591 ])) [0 D.21591_84->slot[i_1].sint8+0 S1 A64]))) lib/FFI/../../xs/API.xs:99 -1
     (nil))
lib/FFI/Platypus.c:771:1: internal compiler error: in extract_insn, at recog.c:2109
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
Preprocessed source stored into /tmp/ccFHeAzR.out file, please attach this to your bugreport.
error building lib/FFI/Platypus.o from 'lib/FFI/Platypus.c' at /usr/share/perl/5.14/ExtUtils/CBuilder/Base.pm line 177.
  PLICEASE/FFI-Platypus-0.43.tar.gz
  ./Build -- NOT OK

**Comment by plicease** [comment]
That looks like a gcc bug to me.

I have in the past been able to get Platypus to install on raspian. 

Couple of things worth trying:

 1. Turn off `alloca` (see https://metacpan.org/pod/FFI::Platypus#FFI_PLATYPUS_NO_ALLOCA )
 2. Use the system libffi.  If you are using raspian, it can be installed with `sudo apt-get install libffi-dev`.  You will also need to reinstall `Alien::FFI` so that it can find it.

I might be willing to accept a patch to work around this, assuming it doesn't adversely affect other platforms.  Please also let me know if you are able to get this working as I would like to at least document the issue.

**Comment by antichef** [comment]
Thanks for the response!  (you can close this one too)

Since I posted, I have tried the install on another Raspberry Pi using Rasbian jessie, and it worked fine.  The one giving me trouble is running wheezy.  I had tried your second suggestion (along with a dozen other things that seemed barely relevant) but not the first.  So far, though, nothing has worked - I've even tried editing a few of the build files directly to make sure that HAVE_ALLOCA is never set to 1, but I still get the error.   I agree it's a gcc bug, which I will attempt to report.

so - this looks like a great reason for me to move the older raspberry pi to jessie, which should solve the issue.  I just wanted to post here to follow up with the additional info and say thanks

**Comment by plicease** [comment]
Thanks for the update good to know that raspian jessie is okay.
