### ISSUE TITLE
Retun data incorrect for attach in Phash::FFI

### ISSUE THREAD

**Issue by lbe** [plicease/FFI-Platypus#71]
I have opened an [rt.cpan ticket](https://rt.cpan.org/Ticket/Display.html?id=120345&results=a706a680eb7c7794fbd1ded3152355d0)t on Phash::FFI documenting a problem with what appears to be a truncation of a uint64 result to a uint32.  While I am experiencing problems with Phash::FFI, I believe the problem is more likely with FFI::Platypus since that is where the heavy lifting is done.  There is very little additional code in Phash::FFI and what is there passes my test.  Phash::FFI is largely a configuration where 99% of the work is done here.

Please review the documentation in the linked ticket and advise if you would like me to try/test anything

Thanks,

lbe

https://rt.cpan.org/Ticket/Display.html?id=120345&results=a706a680eb7c7794fbd1ded3152355d0

**Comment by plicease** [comment]
I can't test this right now because I am in the middle of nowhere Tasmania, but I think the arguments need to be uint64 not the return value.

**Comment by lbe** [comment]
Sir, you are correct!!  I thought I tested this scenario; however, I must have either tested it wrong or misinterpreted the results in my sleep deprived state :)  I will update the the Phash::FFI ticket accordingly.

Thank You!

lbe
