### ISSUE TITLE
Dependency on My::ShareConfig

### ISSUE THREAD

**Issue by jwrightecs** [plicease/FFI-Platypus#72]
$ cpanm FFI::Platypus
--> Working on FFI::Platypus
Fetching http://www.cpan.org/authors/id/P/PL/PLICEASE/FFI-Platypus-0.46.tar.gz ... OK
Configuring FFI-Platypus-0.46 ... OK
==> Found dependencies: My::ShareConfig
! Finding My::ShareConfig on cpanmetadb failed.
! Finding My::ShareConfig (0) on mirror http://www.cpan.org failed.
! Couldn't find module or a distribution My::ShareConfig
! Installing the dependencies failed: Module 'My::ShareConfig' is not installed
! Bailing out the installation for FFI-Platypus-0.46.
$

**Comment by plicease** [comment]
Thank you for reporting this!  This should be fixed in 0.47 on its way to CPAN now.
